framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            query.bus:
                default_middleware:
                    enabled: true
                    allow_no_handlers: false
            infrastructure_job.bus:
                default_middleware:
                    enabled: true
                    allow_no_handlers: false

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: infrastructure_jobs
                        type: direct
                    queues:
                        infrastructure_jobs: ~

        routing:
            App\Shared\Application\InfrastructureJobInterface: async
